// AUTO-GENERATED. Do not edit. `cargo run` regenerates.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getArmed() : Promise<boolean> {
    return await TAURI_INVOKE("get_armed");
},
async toggleArmed() : Promise<boolean> {
    return await TAURI_INVOKE("toggle_armed");
},
async kill() : Promise<void> {
    await TAURI_INVOKE("kill");
},
/**
 * True while a typing playback is in flight. Used by the tray Quit handler
 * to surface a confirm dialog instead of dropping mid-stream.
 */
async isPlaying() : Promise<boolean> {
    return await TAURI_INVOKE("is_playing");
},
/**
 * Whether the keyboard hook is installed and dispatching. The tray uses it to
 * warn instead of failing silently.
 */
async isHookAlive() : Promise<boolean> {
    return await TAURI_INVOKE("is_hook_alive");
},
/**
 * Open the macOS Accessibility pane, re-prompting first so we're listed there
 * and the user has something to toggle. No-op on Windows.
 */
async openAccessibilitySettings() : Promise<void> {
    await TAURI_INVOKE("open_accessibility_settings");
},
/**
 * `tccutil reset Accessibility`, then re-prompt and open the pane. This is the
 * fix for the "approved but not working" state an unsigned update leaves.
 */
async resetAccessibility() : Promise<boolean> {
    return await TAURI_INVOKE("reset_accessibility");
},
async getKeepAwake() : Promise<KeepAwakeState> {
    return await TAURI_INVOKE("get_keep_awake");
},
/**
 * Flip keep-awake and apply the OS assertion. Turning on starts a bounded
 * session, which is what stops the multi-day sessions we saw in the field.
 */
async toggleKeepAwake(durationMins: number | null) : Promise<KeepAwakeState> {
    return await TAURI_INVOKE("toggle_keep_awake", { durationMins });
},
/**
 * Change the default auto-off without toggling. Re-arms a running session so
 * picking "30 min" while already on takes effect immediately.
 */
async setKeepAwakeDuration(durationMins: number) : Promise<KeepAwakeState> {
    return await TAURI_INVOKE("set_keep_awake_duration", { durationMins });
},
/**
 * Opt in/out of restoring keep-awake at launch.
 */
async setKeepAwakeRestore(restore: boolean) : Promise<KeepAwakeState> {
    return await TAURI_INVOKE("set_keep_awake_restore", { restore });
},
async getDiagnostics() : Promise<Diagnostics> {
    return await TAURI_INVOKE("get_diagnostics");
},
/**
 * Check everything between a keypress and a typed character, in order, and
 * stop at the first failure so the UI can name one actionable thing.
 */
async runSelfTest() : Promise<SelfTestReport> {
    return await TAURI_INVOKE("run_self_test");
},
/**
 * Type [`SELF_TEST_PROBE`] into whatever has focus. The window focuses its own
 * field first, making this a real end-to-end check rather than a status read.
 */
async selfTestType() : Promise<void> {
    await TAURI_INVOKE("self_test_type");
},
/**
 * Show the diagnostics window, creating nothing — it's declared in
 * `tauri.conf.json` like the other secondary windows.
 */
async openDiagnostics() : Promise<void> {
    await TAURI_INVOKE("open_diagnostics");
},
/**
 * Read the persisted settings the UI can edit.
 */
async getSettings() : Promise<UiSettings> {
    return await TAURI_INVOKE("get_settings");
},
/**
 * Opt in/out of restoring `armed` at launch. §10.1 stays the default.
 */
async setRestoreArmed(restore: boolean) : Promise<UiSettings> {
    return await TAURI_INVOKE("set_restore_armed", { restore });
},
async listPrompts() : Promise<Prompt[]> {
    return await TAURI_INVOKE("list_prompts");
},
async libraryRoot() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePrompt(prompt: Prompt) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPrompt(name: string | null) : Promise<Result<Prompt, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePrompt(promptId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptEnabled(promptId: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_enabled", { promptId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptPinned(promptId: string, pinned: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_pinned", { promptId, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerOpen() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerSearch(q: string, limit: number | null) : Promise<SearchHit[]> {
    return await TAURI_INVOKE("picker_search", { q, limit });
},
async pickerSelect(promptId: string, mode: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_select", { promptId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerDismiss() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_dismiss") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayOpen(target: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_open", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayQuit() : Promise<void> {
    await TAURI_INVOKE("tray_quit");
},
async trayPopupHide() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_popup_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fire a pinned prompt from the macOS popover. The tray click never activates
 * us, so the user's app still has focus and needs no restore.
 */
async trayFirePrompt(promptId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_fire_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterCurrentVersion() : Promise<string> {
    return await TAURI_INVOKE("updater_current_version");
},
async updaterCheck() : Promise<Result<UpdateInfo, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterInstall() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The user saw an "Install update" affordance. Once per version, so a
 * long-ignored update doesn't inflate the count on every poll.
 */
async updaterAnnounced(version: string) : Promise<void> {
    await TAURI_INVOKE("updater_announced", { version });
},
/**
 * User dismissed the update. Clears the tray badge and suppresses the nag
 * until a newer version lands.
 */
async updaterDismiss(version: string) : Promise<void> {
    await TAURI_INVOKE("updater_dismiss", { version });
},
async captureForegroundApp() : Promise<ForegroundAppInfo> {
    return await TAURI_INVOKE("capture_foreground_app");
},
/**
 * Run a string through the fire-time expansion pipeline for the editor's
 * "Test" button. Tab-stops and selection stay unresolved in a preview.
 */
async expandPromptText(text: string) : Promise<string> {
    return await TAURI_INVOKE("expand_prompt_text", { text });
},
/**
 * Read and parse a `.pp.md`, then copy it into the library root with a fresh
 * id on collision. Returns the prompt so the frontend can select it.
 */
async importPrompt(sourcePath: string) : Promise<Result<Prompt, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_prompt", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a prompt, re-serializing from memory rather than copying the file —
 * otherwise unsaved edits export as the older on-disk version.
 */
async exportPrompt(promptId: string, destPath: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_prompt", { promptId, destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open an http(s) URL in the default browser. Other schemes are rejected, so
 * this can't double as a shell-execute primitive.
 */
async openExternal(url: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_external", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Everything the diagnostics window shows. One round trip, so the UI can't
 * render a half-stale picture of a machine that is mid-repair.
 */
export type Diagnostics = { version: string; os: string; 
/**
 * macOS Accessibility (TCC). Always true where the concept doesn't apply.
 */
accessibilityTrusted: boolean; 
/**
 * The keyboard hook is installed and dispatching.
 */
hookAlive: boolean; 
/**
 * macOS Secure Input is engaged right now, so triggers are gated off.
 */
secureInputActive: boolean; armed: boolean; keepAwake: boolean; prompts: number; enabledPrompts: number; triggers: number; hotkeys: number; libraryRoot: string; logDir: string; 
/**
 * True when the hook cannot work and the user must act.
 */
needsAttention: boolean }
/**
 * Foreground-app identity. All optional: macOS gives bundle_id + name,
 * Windows gives executable + window_title, neither gives both.
 */
export type ForegroundAppInfo = { bundleId: string | null; name: string | null; executable: string | null; windowTitle: string | null }
/**
 * Specta-friendly mirror of `AppError`, so the generated bindings get a clean
 * `{ kind, message }`. `From<AppError>` converts at the command boundary.
 */
export type IpcError = { kind: string; message: string }
/**
 * Keep-awake state for the UI: on/off, the chosen auto-off, and how long is
 * left so the tray can render "1h 12m left" instead of a bare checkmark.
 */
export type KeepAwakeState = { enabled: boolean; 
/**
 * Auto-off for the active session, in minutes. `0` = indefinite.
 */
durationMins: number; 
/**
 * Seconds until auto-off, or `None` when off or indefinite.
 */
remainingSecs: number | null; 
/**
 * The user's default auto-off, applied to the next enable.
 */
defaultMins: number; 
/**
 * Selectable durations, so the UI doesn't hardcode its own list.
 */
choices: number[]; 
/**
 * Whether keep-awake is restored at launch.
 */
restore: boolean }
export type ProfileKind = "sales-engineer" | "fast-presenter" | "thoughtful-ceo" | "custom"
/**
 * One stored prompt loaded from a `.pp.md` file.
 */
export type Prompt = { id: string; name: string; description?: string; triggers: string[]; commit_char?: string; priority?: number; typing_profile?: ProfileKind; typing_overrides?: TypingOverrides; scope?: ScopeFilter | null; filters?: string[]; hotkey?: string | null; tags?: string[]; 
/**
 * Only enabled prompts take part in matching and hotkey registration.
 * Defaults true so existing files keep working untouched.
 */
enabled?: boolean; 
/**
 * The tray shows only pinned prompts (Apple Shortcuts model); unpinned ones
 * still fire from triggers. Defaults false so the tray stays uncrowded.
 */
pinned?: boolean; 
/**
 * Body of the prompt — Markdown source after frontmatter.
 */
body: string }
/**
 * One scope filter from §4.2: app(s), window-title regex, url regex, time-of-day.
 */
export type ScopeFilter = { app: string[]; "window-title-regex": string | null; "url-regex": string | null; "time-of-day": string | null }
export type SearchHit = { prompt_id: string; score: number; 
/**
 * Char offsets (in the haystack) that matched the query. Frontend
 * renders these as highlighted.
 */
highlights: number[] }
/**
 * Result of the pre-flight self test.
 */
export type SelfTestReport = { passed: boolean; steps: SelfTestStep[]; 
/**
 * The string `self_test_type` will inject, for the UI to compare against.
 */
probe: string }
/**
 * One self-test step and whether it passed.
 */
export type SelfTestStep = { name: string; passed: boolean; detail: string }
/**
 * §7.1 `typing-overrides:` mapping.
 */
export type TypingOverrides = { "iki-median-ms": number | null; "typo-rate": number | null; "pause-variance-scale": number | null; "burst-enabled": boolean | null; "typos-enabled": boolean | null; "pre-submit-pause-enabled": boolean | null; "send-final-enter": boolean | null }
/**
 * The editable subset the UI sees.
 */
export type UiSettings = { restoreArmed: boolean; keepAwakeMins: number; restoreKeepAwake: boolean }
/**
 * Result of a `check()`. `version` and `notes` are set only when an update is
 * actually available.
 */
export type UpdateInfo = { available: boolean; currentVersion: string; version: string | null; notes: string | null; 
/**
 * True when the user has already dismissed this exact version.
 */
dismissed: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
