// AUTO-GENERATED. Do not edit. `cargo run` regenerates.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getArmed() : Promise<boolean> {
    return await TAURI_INVOKE("get_armed");
},
async toggleArmed() : Promise<boolean> {
    return await TAURI_INVOKE("toggle_armed");
},
async kill() : Promise<void> {
    await TAURI_INVOKE("kill");
},
async listPrompts() : Promise<Prompt[]> {
    return await TAURI_INVOKE("list_prompts");
},
async libraryRoot() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePrompt(prompt: Prompt) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPrompt(name: string | null) : Promise<Result<Prompt, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePrompt(promptId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptEnabled(promptId: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_enabled", { promptId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerOpen() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerSearch(q: string, limit: number | null) : Promise<SearchHit[]> {
    return await TAURI_INVOKE("picker_search", { q, limit });
},
async pickerSelect(promptId: string, mode: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_select", { promptId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerDismiss() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_dismiss") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayOpen(target: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_open", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayQuit() : Promise<void> {
    await TAURI_INVOKE("tray_quit");
},
async trayPopupHide() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_popup_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Specta-friendly mirror of `AppError`. The IPC layer returns this so the
 * generated TypeScript bindings have a clean structured-error shape:
 * `{ kind: string; message: string }`. `From<AppError>` converts at the
 * command boundary.
 */
export type IpcError = { kind: string; message: string }
export type ProfileKind = "sales-engineer" | "fast-presenter" | "thoughtful-ceo" | "custom"
/**
 * One stored prompt loaded from a `.pp.md` file.
 */
export type Prompt = { id: string; name: string; description?: string; triggers: string[]; commit_char?: string; priority?: number; typing_profile?: ProfileKind; typing_overrides?: TypingOverrides; scope?: ScopeFilter | null; filters?: string[]; hotkey?: string | null; tags?: string[]; 
/**
 * Per-prompt enable flag. When the global `armed` switch is on, only
 * prompts with `enabled: true` participate in trigger-matching and
 * hotkey registration. Defaults to `true` so existing prompts keep
 * working without touching their files.
 */
enabled?: boolean; 
/**
 * Body of the prompt — Markdown source after frontmatter.
 */
body: string }
/**
 * One scope filter from §4.2: app(s), window-title regex, url regex, time-of-day.
 */
export type ScopeFilter = { app: string[]; "window-title-regex": string | null; "url-regex": string | null; "time-of-day": string | null }
export type SearchHit = { prompt_id: string; score: number; 
/**
 * Char offsets (in the haystack) that matched the query. Frontend
 * renders these as highlighted.
 */
highlights: number[] }
/**
 * §7.1 `typing-overrides:` mapping.
 */
export type TypingOverrides = { "iki-median-ms": number | null; "typo-rate": number | null; "pause-variance-scale": number | null; "burst-enabled": boolean | null; "typos-enabled": boolean | null; "pre-submit-pause-enabled": boolean | null; "send-final-enter": boolean | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
