// AUTO-GENERATED. Do not edit. `cargo run` regenerates.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getArmed() : Promise<boolean> {
    return await TAURI_INVOKE("get_armed");
},
async toggleArmed() : Promise<boolean> {
    return await TAURI_INVOKE("toggle_armed");
},
async kill() : Promise<void> {
    await TAURI_INVOKE("kill");
},
/**
 * True while a typing playback is in flight. Used by the tray Quit handler
 * to surface a confirm dialog instead of dropping mid-stream.
 */
async isPlaying() : Promise<boolean> {
    return await TAURI_INVOKE("is_playing");
},
async listPrompts() : Promise<Prompt[]> {
    return await TAURI_INVOKE("list_prompts");
},
async libraryRoot() : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("library_root") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePrompt(prompt: Prompt) : Promise<Result<string, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_prompt", { prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPrompt(name: string | null) : Promise<Result<Prompt, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_prompt", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePrompt(promptId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptEnabled(promptId: string, enabled: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_enabled", { promptId, enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPromptPinned(promptId: string, pinned: boolean) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_prompt_pinned", { promptId, pinned }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerOpen() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_open") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerSearch(q: string, limit: number | null) : Promise<SearchHit[]> {
    return await TAURI_INVOKE("picker_search", { q, limit });
},
async pickerSelect(promptId: string, mode: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_select", { promptId, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pickerDismiss() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("picker_dismiss") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayOpen(target: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_open", { target }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async trayQuit() : Promise<void> {
    await TAURI_INVOKE("tray_quit");
},
async trayPopupHide() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_popup_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run a prompt from the tray (left-click on a pinned row). Hides the popup
 * first, then fires through the picker pipeline at human cadence. The
 * menu-bar / system-tray click never activates the app (`NSNonactivatingPanelMask`
 * on macOS, `WS_EX_NOACTIVATE` on Windows), so the original foreground app
 * is still focused — no focus-restore dance needed.
 */
async trayFirePrompt(promptId: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_fire_prompt", { promptId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterCurrentVersion() : Promise<string> {
    return await TAURI_INVOKE("updater_current_version");
},
async updaterCheck() : Promise<Result<UpdateInfo, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updaterInstall() : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("updater_install") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async captureForegroundApp() : Promise<ForegroundAppInfo> {
    return await TAURI_INVOKE("capture_foreground_app");
},
/**
 * Run a string through the same placeholder + expression pipeline used at
 * fire time. Powers the editor's "Test" button. Errors inside `${{ … }}`
 * blocks surface inline as `[expr error: …]` (consistent with how typing
 * would handle them). Tab-stops, choices, and selection are not resolved
 * here — the body is rendered as if the user had no clipboard / selection
 * context, which is the right default for an authoring preview.
 */
async expandPromptText(text: string) : Promise<string> {
    return await TAURI_INVOKE("expand_prompt_text", { text });
},
/**
 * Import a `.pp.md` file: read it, parse it (validates frontmatter),
 * then copy into the library root with a fresh ID if one already exists.
 * Returns the parsed `Prompt` so the frontend can select it immediately.
 */
async importPrompt(sourcePath: string) : Promise<Result<Prompt, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_prompt", { sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a prompt to a user-chosen path. Re-serializes the in-memory
 * `Prompt` to `.pp.md` rather than copying the source file, so unsaved
 * edits in the library don't get exported as the older on-disk version.
 */
async exportPrompt(promptId: string, destPath: string) : Promise<Result<null, IpcError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_prompt", { promptId, destPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Identifying info for a foreground app. Every field is optional because
 * platforms surface different subsets — Mac always has bundle_id+name,
 * Windows always has executable+window_title, neither has both.
 */
export type ForegroundAppInfo = { bundleId: string | null; name: string | null; executable: string | null; windowTitle: string | null }
/**
 * Specta-friendly mirror of `AppError`. The IPC layer returns this so the
 * generated TypeScript bindings have a clean structured-error shape:
 * `{ kind: string; message: string }`. `From<AppError>` converts at the
 * command boundary.
 */
export type IpcError = { kind: string; message: string }
export type ProfileKind = "sales-engineer" | "fast-presenter" | "thoughtful-ceo" | "custom"
/**
 * One stored prompt loaded from a `.pp.md` file.
 */
export type Prompt = { id: string; name: string; description?: string; triggers: string[]; commit_char?: string; priority?: number; typing_profile?: ProfileKind; typing_overrides?: TypingOverrides; scope?: ScopeFilter | null; filters?: string[]; hotkey?: string | null; tags?: string[]; 
/**
 * Per-prompt enable flag. When the global `armed` switch is on, only
 * prompts with `enabled: true` participate in trigger-matching and
 * hotkey registration. Defaults to `true` so existing prompts keep
 * working without touching their files.
 */
enabled?: boolean; 
/**
 * Tray surfacing flag. The menu-bar popup shows ONLY pinned prompts
 * (Apple Shortcuts model). Unpinned prompts still live in the library
 * and still fire from triggers — they're just not in the tray menu.
 * Defaults to `false` so existing prompts don't crowd the tray.
 */
pinned?: boolean; 
/**
 * Body of the prompt — Markdown source after frontmatter.
 */
body: string }
/**
 * One scope filter from §4.2: app(s), window-title regex, url regex, time-of-day.
 */
export type ScopeFilter = { app: string[]; "window-title-regex": string | null; "url-regex": string | null; "time-of-day": string | null }
export type SearchHit = { prompt_id: string; score: number; 
/**
 * Char offsets (in the haystack) that matched the query. Frontend
 * renders these as highlighted.
 */
highlights: number[] }
/**
 * §7.1 `typing-overrides:` mapping.
 */
export type TypingOverrides = { "iki-median-ms": number | null; "typo-rate": number | null; "pause-variance-scale": number | null; "burst-enabled": boolean | null; "typos-enabled": boolean | null; "pre-submit-pause-enabled": boolean | null; "send-final-enter": boolean | null }
/**
 * Result of a `check()` call. `version` and `notes` are populated only
 * when an update is available; otherwise `available` is `false` and the
 * fields are `None`.
 */
export type UpdateInfo = { available: boolean; currentVersion: string; version: string | null; notes: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
