//! Theme-adaptive tray icon: Windows has no template-image concept, so we ship
//! light and dark PNGs and swap on `SystemUsesLightTheme`.
//!
//! Polled every 5s instead of handling WM_SETTINGCHANGE — themes change rarely,
//! and the message path needs a window class and a pump.

use tauri::AppHandle;

/// Embedded at compile time from `src-tauri/icons/`, regenerated by
/// `scripts/generate-win-tray-icons.py`.
pub const ICON_LIGHT: &[u8] = include_bytes!("../../../icons/tray-icon-win-light.png");
pub const ICON_DARK: &[u8] = include_bytes!("../../../icons/tray-icon-win-dark.png");

/// True when the tray backdrop is light. Defaults to false on any registry
/// error, since a black glyph on Win11's default dark disappears entirely.
pub fn read_uses_light_theme() -> bool {
    use windows::core::PCWSTR;
    use windows::Win32::Foundation::ERROR_SUCCESS;
    use windows::Win32::System::Registry::{
        RegCloseKey, RegOpenKeyExW, RegQueryValueExW, HKEY, HKEY_CURRENT_USER, KEY_READ,
        REG_VALUE_TYPE,
    };

    let subkey: Vec<u16> = "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\0"
        .encode_utf16()
        .collect();
    let value_name: Vec<u16> = "SystemUsesLightTheme\0".encode_utf16().collect();

    unsafe {
        let mut hkey = HKEY::default();
        let open = RegOpenKeyExW(
            HKEY_CURRENT_USER,
            PCWSTR(subkey.as_ptr()),
            0,
            KEY_READ,
            &mut hkey,
        );
        if open != ERROR_SUCCESS {
            return false;
        }
        let mut data: u32 = 0;
        let mut data_size: u32 = std::mem::size_of::<u32>() as u32;
        let mut value_type = REG_VALUE_TYPE::default();
        let query = RegQueryValueExW(
            hkey,
            PCWSTR(value_name.as_ptr()),
            None,
            Some(&mut value_type),
            Some(&mut data as *mut u32 as *mut u8),
            Some(&mut data_size),
        );
        let _ = RegCloseKey(hkey);
        if query != ERROR_SUCCESS {
            return false;
        }
        data == 1
    }
}

/// Pick the right icon bytes for the current Windows theme.
pub fn pick_icon_bytes() -> &'static [u8] {
    if read_uses_light_theme() {
        ICON_LIGHT
    } else {
        ICON_DARK
    }
}

/// Poll `SystemUsesLightTheme` every 5s and swap the icon on change; no-op
/// otherwise. Assumes the tray id `"main"` set in `app::setup::run`.
pub fn install_theme_watcher(app: AppHandle) {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;
    use std::thread;
    use std::time::Duration;

    // Only swap on transition. A toggle between tray creation and the first
    // tick is caught on the next one.
    let last_uses_light = Arc::new(AtomicBool::new(read_uses_light_theme()));

    thread::Builder::new()
        .name("prompt-player-tray-theme-watch".into())
        .spawn(move || loop {
            thread::sleep(Duration::from_secs(5));
            let now_uses_light = read_uses_light_theme();
            let prev = last_uses_light.load(Ordering::Relaxed);
            if now_uses_light == prev {
                continue;
            }
            last_uses_light.store(now_uses_light, Ordering::Relaxed);

            tracing::info!(
                "Windows theme changed (uses_light={}); swapping tray icon",
                now_uses_light
            );
            // None during teardown, which we treat as "stop polling" and exit.
            if app.tray_by_id(crate::tray_icon::TRAY_ID).is_none() {
                tracing::warn!("tray missing — tray-theme watcher exiting");
                return;
            }
            // Through `tray_icon::refresh` so a theme swap can't wipe the
            // attention badge; it re-reads the theme and re-applies both.
            crate::tray_icon::refresh(&app);
        })
        .expect("spawn tray theme watcher thread");
}
