//! Theme-adaptive tray icon for Windows.
//!
//! Win11's notification flyout backdrop is dark by default; a black-on-
//! transparent tray icon (the macOS template format) is nearly invisible
//! against it. This module ships two variants of the tray icon
//! (`tray-icon-win-light.png` = black glyph for light theme,
//! `tray-icon-win-dark.png` = white glyph for dark theme), reads the
//! current Windows theme from the registry, and swaps the tray icon
//! when the user toggles the system theme at runtime.
//!
//! macOS doesn't go through this module — `icon_as_template(true)` lets
//! AppKit handle the inversion natively.
//!
//! Detection strategy: poll the registry every 5 seconds. Themes change
//! rarely (a user manually toggles in Settings); a 5s lag is invisible.
//! This deliberately avoids the WM_SETTINGCHANGE message-only-window dance
//! — that would shave off the 5s lag at the cost of registering a window
//! class, running a message pump, and managing a global state pointer.

use tauri::{AppHandle, Manager};

/// Embedded at compile time — these match what's in `src-tauri/icons/`.
/// Regenerated by `scripts/generate-win-tray-icons.py` from the canonical
/// `tray-icon.png`.
pub const ICON_LIGHT: &[u8] = include_bytes!("../../../icons/tray-icon-win-light.png");
pub const ICON_DARK: &[u8] = include_bytes!("../../../icons/tray-icon-win-dark.png");

/// Read `HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\
/// SystemUsesLightTheme`. Returns `true` when the system tray uses a light
/// backdrop (dark glyph reads), `false` for dark backdrop (white glyph reads).
///
/// Defaults to `false` (assume dark theme) on any registry error — Win11's
/// out-of-the-box default is dark, so erring that way is the better
/// fallback than picking a black glyph that disappears on most installs.
pub fn read_uses_light_theme() -> bool {
    use windows::core::PCWSTR;
    use windows::Win32::Foundation::ERROR_SUCCESS;
    use windows::Win32::System::Registry::{
        RegCloseKey, RegOpenKeyExW, RegQueryValueExW, HKEY, HKEY_CURRENT_USER, KEY_READ,
        REG_VALUE_TYPE,
    };

    let subkey: Vec<u16> = "Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\0"
        .encode_utf16()
        .collect();
    let value_name: Vec<u16> = "SystemUsesLightTheme\0".encode_utf16().collect();

    unsafe {
        let mut hkey = HKEY::default();
        let open = RegOpenKeyExW(
            HKEY_CURRENT_USER,
            PCWSTR(subkey.as_ptr()),
            0,
            KEY_READ,
            &mut hkey,
        );
        if open != ERROR_SUCCESS {
            return false;
        }
        let mut data: u32 = 0;
        let mut data_size: u32 = std::mem::size_of::<u32>() as u32;
        let mut value_type = REG_VALUE_TYPE::default();
        let query = RegQueryValueExW(
            hkey,
            PCWSTR(value_name.as_ptr()),
            None,
            Some(&mut value_type),
            Some(&mut data as *mut u32 as *mut u8),
            Some(&mut data_size),
        );
        let _ = RegCloseKey(hkey);
        if query != ERROR_SUCCESS {
            return false;
        }
        data == 1
    }
}

/// Pick the right icon bytes for the current Windows theme.
pub fn pick_icon_bytes() -> &'static [u8] {
    if read_uses_light_theme() {
        ICON_LIGHT
    } else {
        ICON_DARK
    }
}

/// Spawn a poller that re-reads `SystemUsesLightTheme` every 5s and swaps
/// the tray icon when it changes. Idempotent in the no-change case (no
/// `set_icon` call at all). Tray icon ID is assumed to be `"main"` —
/// matches the value in `app::setup::run`'s `TrayIconBuilder::with_id`.
pub fn install_theme_watcher(app: AppHandle) {
    use std::sync::atomic::{AtomicBool, Ordering};
    use std::sync::Arc;
    use std::thread;
    use std::time::Duration;

    // Track current state so we only swap on transition. Initialized from
    // the same read we made at startup; if the user toggled theme between
    // tray creation and this thread's first tick, we'll catch it on the
    // next tick — a few seconds of stale icon is acceptable.
    let last_uses_light = Arc::new(AtomicBool::new(read_uses_light_theme()));

    thread::Builder::new()
        .name("prompt-player-tray-theme-watch".into())
        .spawn(move || loop {
            thread::sleep(Duration::from_secs(5));
            let now_uses_light = read_uses_light_theme();
            let prev = last_uses_light.load(Ordering::Relaxed);
            if now_uses_light == prev {
                continue;
            }
            last_uses_light.store(now_uses_light, Ordering::Relaxed);

            let bytes = if now_uses_light {
                ICON_LIGHT
            } else {
                ICON_DARK
            };
            tracing::info!(
                "Windows theme changed (uses_light={}); swapping tray icon",
                now_uses_light
            );
            // `tray_by_id` is the modern Tauri 2 path. The tray was built
            // with id "main"; this returns None during teardown which we
            // treat as "stop polling" by exiting the thread.
            let Some(tray) = app.tray_by_id("main") else {
                tracing::warn!("tray 'main' missing — tray-theme watcher exiting");
                return;
            };
            match tauri::image::Image::from_bytes(bytes) {
                Ok(img) => {
                    if let Err(e) = tray.set_icon(Some(img)) {
                        tracing::warn!("set_icon failed: {}", e);
                    }
                }
                Err(e) => tracing::warn!("decode tray icon bytes failed: {}", e),
            }
        })
        .expect("spawn tray theme watcher thread");
}
